import i18nConfig from "../../../i18nConfig";
import Footer from "@/components/footer/Footer";

import type { Metadata } from "next";

import "../globals.css";
import { Navbar } from "@/components/navbar/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export async function generateMetadata({
//   params,
// }: {
//   params: { locale: string };
// }): Promise<Metadata> {
//   const { locale } = await params;

//   if (!i18nConfig.locales.includes(locale)) {
//     notFound();
//   }

//   const { t } = await initTranslations(locale, ["metadata"]);

//   return {
//     title: t("title"), // assuming you have this key
//     description: t("description"),
//   };
// }

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;

  return (
      <div className="relative flex min-h-screen flex-col bg-black">
        <Navbar />
        <main className="flex-1">{children}</main>
        <Footer />
      </div>
  );
}
